### PR TITLE
Use keys and certs generated from trust rather than openssl.

### PR DESCRIPTION
**Pull request by joylatten**
Signed-off-by: Joy Latten <jlatten@cisco.com>

### CODE REVIEW

**Comment by hallyn** [comment]
Looks fine - but can I ask what is the convention regarding privkey vs key.pem?

There is such a thing as pulling the pubkey.pem out of the cert, right?  So privkey.pem made sense to me - but if it's unorthodox, i'm definitely fine with this.  Just asking.

**Comment by joylatten** [comment]
I preferred "privkey.pem" too. My only reasoning for changing it to "key.pem" was for consistency. In atomix we use "key.pem" and so I thought to be consistent with atomix. But if you think its ok, I can happily change that back to "privkey.pem". Let me know.

**Comment by hallyn** [comment]
Yes, please rename them to privkey.pem.

**Comment by joylatten** [comment]
ok done. It is "privkey.pem" instead of "key.pem".

**Comment by hallyn** [comment]
Thanks - part of me did prefer 'sampleproject' to 'manifest' for the sample manifest signing key+cert directory, but manifest vs manifestCA may lead people to the right place faster, so I guess let's stick with this.

**Pull request merged**
